name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKEREMAIL }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t reshadhabibzai/custom-nginx-plus-efs:latest -f Dockerfile .

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKEREMAIL }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push reshadhabibzai/custom-nginx-plus-efs:latest
