name: Notify SQS

on:
  workflow_dispatch:

jobs:
  notify-sqs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send message to SQS
        run: |
          IMAGE_NAME="157363554348.dkr.ecr.us-west-2.amazonaws.com/brewedawakening:latest"
          CLUSTER_NAME="${{ secrets.AWS_CLUSTERNAME }}"
          SERVICE_NAME="${{ secrets.AWS_SERVICENAME }}"
          MESSAGE="{\"Brewed_Awakening_Cluster\": \"$CLUSTER_NAME\", \"BrewedAwakeningService\": \"$SERVICE_NAME\", \"dockerimagename\": \"$IMAGE_NAME\", \"version\": \"$IMAGE_VERSION\"}"
          aws sqs send-message --queue-url "https://sqs.us-west-2.amazonaws.com/157363554348/github-workflow-ecr-auto-pull-and-run-on-ecs" --message-body "$MESSAGE"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
